name: Build and Release exe

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Single File EXE
      run: dotnet publish -c Release -r win-x64 -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:SelfContained=true -o ./publish

    - name: Upload EXE to Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./publish/HardwareDiagnosticsTool.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
